### ISSUE TITLE
No .exe, only python file, installation not clear at all.

### ISSUE THREAD

**Issue by Ehtz** [saschiwy/HeicConverter#2]
Looks like a great idea but a Tkinter GUI would be fantastic.

**Comment by saschiwy** [comment]
Hi Ehtz, thanks a lot

The .exe is available in the releases section:
[https://github.com/saschiwy/HeicConverter/releases/tag/v0.0.1](https://github.com/saschiwy/HeicConverter/releases/tag/v0.0.1)

Let me know if you found it.

I wanted to use a script for automatization. But I would appreciate if you create a GUI via a PR.
Best Sascha

**Comment by saschiwy** [comment]
GUI Available with: [Release v0.1.0](https://github.com/saschiwy/HeicConverter/releases/tag/v0.1.0)
