### ISSUE TITLE
Missing installation script

### ISSUE THREAD

**Issue by t-pawelb** [saschiwy/HeicConverter#3]
hi, nice tool but missing installation script.
It would be nice to have a list of dependenices to install in requirements.txt for example

```
pillow_heif==0.14.0
piexif==1.1.3
```

**Comment by saschiwy** [comment]
Hey  @t-pawelb 

Thanks a lot.

You are absolutely right. I added the requirements.txt and added a note to readme in commit:  [3fbefbb](https://github.com/saschiwy/HeicConverter/commit/3fbefbb3fe5adcbf8856be0516fef9c9ae917da3)

Does this close the issue for you?
