### ISSUE TITLE
Windows Send to

### ISSUE THREAD

**Issue by Raboo** [saschiwy/HeicConverter#4]
Hi,

Thanks for this simple but useful tool.

I would like to use your tool with Windows "[Send to](https://www.groovypost.com/howto/customize-add-remove-items-sendto-menu-windows-10/)".

Doesn't seem to work. You have any idea on how to make it work with "Send to"?

**Comment by saschiwy** [comment]
Hi @Raboo 

I created a new release [v0.0.2](https://github.com/saschiwy/HeicConverter/releases/tag/v0.0.2). I tried to use it via send to and was able to do so.

Open a file browser and open the path: `%APPDATA%\Microsoft\Windows\SendTo`
Add a shortcut to the downloaded exe and use it as desired.

![grafik](https://github.com/saschiwy/HeicConverter/assets/12509764/46289b17-57c0-401e-a77d-6fc60867e2ba)

![grafik](https://github.com/saschiwy/HeicConverter/assets/12509764/618cba47-cee6-432d-b4a6-686790137811)

![grafik](https://github.com/saschiwy/HeicConverter/assets/12509764/cd309d84-bf41-47aa-a9d6-c9ba3bd2435e)
