### ISSUE TITLE
Error with 0Kb files

### ISSUE THREAD

**Issue by storresano** [saschiwy/HeicConverter#6]
Hello, thanks for making this script!

When it finds photos with size 0 (probably corrupt) it throws an unhandled exception and stops.

Thanks

**Comment by saschiwy** [comment]
Hi @storresano,

Thank you for your finding and your comment :)

The newest Relese [v0.1.0](https://github.com/saschiwy/HeicConverter/releases/tag/v0.1.0) will fix this.

Kind Regards
Sascha
